# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://libotti.github.io/
baseurl: /
title: Robert Libotti
author: Robert Libotti
description: Blog Pessoal e Currículo
avatar: profile.png
email: robert.libotti@gmail.com
github: libotti # username
twitter: username
linkedin: username
stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
disqus: username
google_analytics: UA-69391421-1

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
name: Chris Turner
email: christurner@me.com
email_full: mailto:youremail@me.com
website: github.io/sustain
website_full: https://biomadeira.github.io/sustain
github: trending
twitter: twitter
tel: +44 0000 000000
tel_full: tel:+440000000000
google_maps: 'https://www.google.co.uk/maps/place/44+Perth+St,+Edinburgh,+Edinburgh+City+EH3+5BL'
address: 44 Perth Street
postcode: EH3 5BL
city: Edinburgh
country: United Kingdom




# needed for travis-ci build
exclude: [vendor]
