# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://libotti.github.io/
baseurl: /
title: Robert Libotti
author: Robert Libotti
description: Blog Pessoal e Currículo
avatar: profile.png
email: robert.libotti@gmail.com
github: libotti # username
twitter: username
linkedin: username
stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
disqus: username
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
